// <auto-generated />
using System;
using Holcim.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Holcim.Persistence.Migrations
{
    [DbContext(typeof(DataBaseService))]
    [Migration("20241204063633_trazabilidadrfx")]
    partial class trazabilidadrfx
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Holcim.Domain.Entities.Acciones.Acciones", b =>
                {
                    b.Property<Guid>("IdAcciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAcciones");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.AccionesMenu.AccionesMenu", b =>
                {
                    b.Property<Guid>("IdAccionesMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccionesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdAccionesMenu");

                    b.HasIndex("AccionesId");

                    b.HasIndex("MenuId");

                    b.HasIndex("RolId");

                    b.ToTable("AccionesMenu");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Archivos.ArchivoSobre", b =>
                {
                    b.Property<Guid>("IdArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TipoArchivoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdArchivo");

                    b.HasIndex("TipoArchivoId");

                    b.ToTable("ArchivoSobre");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Archivos.ValoresArchivo", b =>
                {
                    b.Property<Guid>("IdValoresArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdValoresArchivo");

                    b.ToTable("ValoresArchivo");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Cargo.Cargo", b =>
                {
                    b.Property<Guid>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCargo");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Correo.Correo", b =>
                {
                    b.Property<Guid>("IdCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Html")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCorreo");

                    b.ToTable("Correo");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.CuentaAdmin.CuentaAdmin", b =>
                {
                    b.Property<Guid>("IdCuentaAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdCuentaAdmin");

                    b.HasIndex("CargoId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("PaisId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CuentaAdmin");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Dependencia.Departamento", b =>
                {
                    b.Property<Guid>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDepartamento");

                    b.ToTable("Dependencia");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Estado.Estado", b =>
                {
                    b.Property<Guid>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TipoEstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdEstado");

                    b.HasIndex("TipoEstadoId");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Idioma.Idioma", b =>
                {
                    b.Property<Guid>("IdIdioma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdIdioma");

                    b.ToTable("Idioma");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Informes.Informes", b =>
                {
                    b.Property<Guid>("IdInformes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdInformes");

                    b.ToTable("Informes");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Informes.InformesRol", b =>
                {
                    b.Property<Guid>("IdInformesRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InformesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdInformesRol");

                    b.HasIndex("InformesId");

                    b.HasIndex("RolId");

                    b.ToTable("InformesRol");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Item.Item", b =>
                {
                    b.Property<Guid>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdItem");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Item.ItemDetalle", b =>
                {
                    b.Property<Guid>("IdItemDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PscsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnidadMedidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("valorUnidad")
                        .HasColumnType("int");

                    b.HasKey("IdItemDetalle");

                    b.HasIndex("ItemId");

                    b.HasIndex("PscsId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("ItemDetalle");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Item.ItemPregunta", b =>
                {
                    b.Property<Guid>("IdItemPregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("preguntaArchivoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdItemPregunta");

                    b.HasIndex("ItemId");

                    b.HasIndex("preguntaArchivoId");

                    b.ToTable("ItemPregunta");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Menu.Menu", b =>
                {
                    b.Property<Guid>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdPadre")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathFront")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMenu");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Moneda.Moneda", b =>
                {
                    b.Property<Guid>("IdMoneda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMoneda");

                    b.ToTable("Moneda");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Notificaciones.Notificaciones", b =>
                {
                    b.Property<Guid>("IdNotificaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNotificaciones");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Pais.Pais", b =>
                {
                    b.Property<Guid>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Indicativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPais");

                    b.HasIndex("RegionId");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.PreguntaArchivo.PreguntaArchivo", b =>
                {
                    b.Property<Guid>("IdPreguntaArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Afirmacion")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ArchivoSobreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pregunta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Requerido")
                        .HasColumnType("bit");

                    b.Property<string>("RutaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ValoresArchivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValoresArchivoJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPreguntaArchivo");

                    b.HasIndex("ArchivoSobreId");

                    b.HasIndex("ValoresArchivoId");

                    b.ToTable("PreguntaArchivo");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.PreguntaArchivo.PreguntaSobreRfx", b =>
                {
                    b.Property<Guid>("IdPreguntaSobreRfx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PreguntaArchivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RfxId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPreguntaSobreRfx");

                    b.HasIndex("PreguntaArchivoId");

                    b.HasIndex("RfxId");

                    b.ToTable("PreguntaSobreRfx");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Proveedor.Proveedor", b =>
                {
                    b.Property<Guid>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdiomaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistroMercantil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZonaHorariaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdProveedor");

                    b.HasIndex("IdiomaId");

                    b.HasIndex("PaisId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ZonaHorariaId");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Pscs.CategoriaPsc", b =>
                {
                    b.Property<Guid>("IdCategoriaPsc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoriaPsc");

                    b.ToTable("CategoriaPsc");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Pscs.GrupoPsc", b =>
                {
                    b.Property<Guid>("IdGrupoPsc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGrupoPsc");

                    b.ToTable("GrupoPsc");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Pscs.Pscs", b =>
                {
                    b.Property<Guid>("IdPscs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaPscId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GrupoPscId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PscsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PscsNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPscs");

                    b.HasIndex("CategoriaPscId");

                    b.HasIndex("GrupoPscId");

                    b.ToTable("Pscs");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Region.Region", b =>
                {
                    b.Property<Guid>("IdRegion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRegion");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Rfx.Rfx", b =>
                {
                    b.Property<Guid>("IdRfx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetalleUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicial")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MonedaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoRfxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioCreacion")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdRfx");

                    b.HasIndex("EstadoId");

                    b.HasIndex("MonedaId");

                    b.HasIndex("RegionId");

                    b.HasIndex("TipoRfxId");

                    b.ToTable("Rfx");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Rfx.RfxItem", b =>
                {
                    b.Property<Guid>("IdRfxItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RfxId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdRfxItem");

                    b.HasIndex("ItemId");

                    b.HasIndex("RfxId");

                    b.ToTable("RfxItem");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Rfx.TrazabilidadRfx", b =>
                {
                    b.Property<Guid>("IdTrazabilidadRfx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RfxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdTrazabilidadRfx");

                    b.HasIndex("EstadoId");

                    b.HasIndex("RfxId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TrazabilidadRfx");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Rol.Rol", b =>
                {
                    b.Property<Guid>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.RolMenu.RolMenu", b =>
                {
                    b.Property<Guid>("RolMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolMenuId");

                    b.HasIndex("MenuId");

                    b.HasIndex("RolId");

                    b.ToTable("RolMenu");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.TipoArchivo.TipoArchivo", b =>
                {
                    b.Property<Guid>("IdTipoArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoArchivo");

                    b.ToTable("TipoArchivo");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.TipoArchivo.TipoArchivoRfx", b =>
                {
                    b.Property<Guid>("IdTipoArchivoRfx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoArchivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoRfxId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdTipoArchivoRfx");

                    b.HasIndex("TipoArchivoId");

                    b.HasIndex("TipoRfxId");

                    b.ToTable("TipoArchivoRfx");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.TipoEstado.TipoEstado", b =>
                {
                    b.Property<Guid>("IdTipoEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("IdTipoEstado");

                    b.ToTable("TipoEstado");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.TipoRfx.TipoRfx", b =>
                {
                    b.Property<Guid>("IdTipoRfx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoRfx");

                    b.ToTable("TipoRfx");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.TipoUsuario.TipoUsuario", b =>
                {
                    b.Property<Guid>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoUsuario");

                    b.ToTable("TipoUsuario");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.UnidadMedida.UnidadMedida", b =>
                {
                    b.Property<Guid>("IdUnidadMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UdmCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UdmDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUnidadMedida");

                    b.ToTable("UnidadMedida");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Usuario.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Aprobador")
                        .HasColumnType("bit");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBloqueo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TipoUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuario");

                    b.HasIndex("RolId");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Usuario.UsuarioToken", b =>
                {
                    b.Property<Guid>("IdUsuarioToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Idusuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuarioToken");

                    b.ToTable("UsuarioToken");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.UsuarioNotificaciones.UsuarioNotificaciones", b =>
                {
                    b.Property<Guid>("IdUsuarioNotificaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NotificacionesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuarioNotificaciones");

                    b.HasIndex("NotificacionesId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioNotificaciones");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.ZonaHoraria.ZonaHoraria", b =>
                {
                    b.Property<Guid>("IdZonaHoraria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdZonaHoraria");

                    b.ToTable("ZonaHoraria");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.ZonaHoraria.ZonaHorariaPais", b =>
                {
                    b.Property<Guid>("IdZonaHorariaPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZonaHorariaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdZonaHorariaPais");

                    b.HasIndex("PaisId");

                    b.HasIndex("ZonaHorariaId");

                    b.ToTable("ZonaHorariaPais");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.AccionesMenu.AccionesMenu", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Acciones.Acciones", "Acciones")
                        .WithMany()
                        .HasForeignKey("AccionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Menu.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Rol.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acciones");

                    b.Navigation("Menu");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Archivos.ArchivoSobre", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.TipoArchivo.TipoArchivo", "TipoArchivo")
                        .WithMany()
                        .HasForeignKey("TipoArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoArchivo");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.CuentaAdmin.CuentaAdmin", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Cargo.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Dependencia.Departamento", "Dependencia")
                        .WithMany()
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("Holcim.Domain.Entities.Pais.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Usuario.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Dependencia");

                    b.Navigation("Pais");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Estado.Estado", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.TipoEstado.TipoEstado", "TipoEstado")
                        .WithMany()
                        .HasForeignKey("TipoEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoEstado");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Informes.InformesRol", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Informes.Informes", "Informes")
                        .WithMany()
                        .HasForeignKey("InformesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Rol.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Informes");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Item.ItemDetalle", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Item.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Pscs.Pscs", "Pscs")
                        .WithMany()
                        .HasForeignKey("PscsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.UnidadMedida.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Pscs");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Item.ItemPregunta", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Item.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.PreguntaArchivo.PreguntaArchivo", "preguntaArchivo")
                        .WithMany()
                        .HasForeignKey("preguntaArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("preguntaArchivo");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Pais.Pais", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Region.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.PreguntaArchivo.PreguntaArchivo", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Archivos.ArchivoSobre", "ArchivoSobre")
                        .WithMany()
                        .HasForeignKey("ArchivoSobreId");

                    b.HasOne("Holcim.Domain.Entities.Archivos.ValoresArchivo", "ValoresArchivo")
                        .WithMany()
                        .HasForeignKey("ValoresArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivoSobre");

                    b.Navigation("ValoresArchivo");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.PreguntaArchivo.PreguntaSobreRfx", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.PreguntaArchivo.PreguntaArchivo", "PreguntaArchivo")
                        .WithMany()
                        .HasForeignKey("PreguntaArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Rfx.Rfx", "Rfx")
                        .WithMany()
                        .HasForeignKey("RfxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreguntaArchivo");

                    b.Navigation("Rfx");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Proveedor.Proveedor", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Idioma.Idioma", "Idioma")
                        .WithMany()
                        .HasForeignKey("IdiomaId");

                    b.HasOne("Holcim.Domain.Entities.Pais.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Usuario.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.ZonaHoraria.ZonaHoraria", "ZonaHoraria")
                        .WithMany()
                        .HasForeignKey("ZonaHorariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idioma");

                    b.Navigation("Pais");

                    b.Navigation("Usuario");

                    b.Navigation("ZonaHoraria");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Pscs.Pscs", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Pscs.CategoriaPsc", "CategoriaPsc")
                        .WithMany()
                        .HasForeignKey("CategoriaPscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Pscs.GrupoPsc", "GrupoPsc")
                        .WithMany()
                        .HasForeignKey("GrupoPscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPsc");

                    b.Navigation("GrupoPsc");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Rfx.Rfx", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Estado.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Moneda.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Region.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.TipoRfx.TipoRfx", "TipoRfx")
                        .WithMany()
                        .HasForeignKey("TipoRfxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Moneda");

                    b.Navigation("Region");

                    b.Navigation("TipoRfx");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Rfx.RfxItem", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Item.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Rfx.Rfx", "Rfx")
                        .WithMany()
                        .HasForeignKey("RfxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Rfx");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Rfx.TrazabilidadRfx", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Estado.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Rfx.Rfx", "Rfx")
                        .WithMany()
                        .HasForeignKey("RfxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Usuario.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Rfx");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.RolMenu.RolMenu", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Menu.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Rol.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.TipoArchivo.TipoArchivoRfx", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.TipoArchivo.TipoArchivo", "TipoArchivo")
                        .WithMany()
                        .HasForeignKey("TipoArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.TipoRfx.TipoRfx", "TipoRfx")
                        .WithMany()
                        .HasForeignKey("TipoRfxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoArchivo");

                    b.Navigation("TipoRfx");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.Usuario.Usuario", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Rol.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.TipoUsuario.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.UsuarioNotificaciones.UsuarioNotificaciones", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Notificaciones.Notificaciones", "Notificaciones")
                        .WithMany()
                        .HasForeignKey("NotificacionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.Usuario.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notificaciones");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.ZonaHoraria.ZonaHorariaPais", b =>
                {
                    b.HasOne("Holcim.Domain.Entities.Pais.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.Domain.Entities.ZonaHoraria.ZonaHoraria", "ZonaHoraria")
                        .WithMany()
                        .HasForeignKey("ZonaHorariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");

                    b.Navigation("ZonaHoraria");
                });
#pragma warning restore 612, 618
        }
    }
}
