// <auto-generated />
using System;
using Holcim.Provider.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Holcim.Provider.Persistence.Migrations
{
    [DbContext(typeof(DataBaseService))]
    [Migration("20250117193119_itemrespuesta")]
    partial class itemrespuesta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Holcim.Provider.Domain.Entities.ProveedorUsuario", b =>
                {
                    b.Property<Guid>("IdProveedorUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdProveedorUsuario");

                    b.ToTable("ProveedorUsuario");
                });

            modelBuilder.Entity("Holcim.Provider.Domain.Entities.RespuestaPregunta", b =>
                {
                    b.Property<Guid>("IdRespuestaPregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PreguntaArchivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Respuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RfxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrlArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRespuestaPregunta");

                    b.ToTable("RespuestaPregunta");
                });

            modelBuilder.Entity("Holcim.Provider.Domain.Entities.RespuestaPreguntaPorcentaje", b =>
                {
                    b.Property<Guid>("IdRespuestaPreguntaPorcentaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Calificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RfxId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdRespuestaPreguntaPorcentaje");

                    b.ToTable("RespuestaPreguntaPorcentaje");
                });
#pragma warning restore 612, 618
        }
    }
}
