// <auto-generated />
using System;
using Holcim.AuctionService.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Holcim.AuctionService.Persistence.Migrations
{
    [DbContext(typeof(DataBaseService))]
    [Migration("20241217193257_addZonaHoraria")]
    partial class addZonaHoraria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Correo.Correo", b =>
                {
                    b.Property<Guid>("IdCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Html")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCorreo");

                    b.ToTable("Correo");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.ItemSubasta.ItemSubasta", b =>
                {
                    b.Property<Guid>("IdItemSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdItemSubasta");

                    b.HasIndex("SubastaId");

                    b.ToTable("ItemSubasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Region.RegionSubasta", b =>
                {
                    b.Property<Guid>("IdRegionSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRegion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdRegionSubasta");

                    b.HasIndex("SubastaId");

                    b.ToTable("RegionSubasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Subasta.InvitacionProveedorSubasta", b =>
                {
                    b.Property<Guid>("IdInvitacionProveedorSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdInvitacionProveedorSubasta");

                    b.HasIndex("SubastaId");

                    b.ToTable("InvitacionProveedorSubasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Subasta.PreguntaSobreSubasta", b =>
                {
                    b.Property<Guid>("IdPreguntaSobreSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PreguntaArchivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPreguntaSobreSubasta");

                    b.HasIndex("SubastaId");

                    b.ToTable("PreguntaSobreSubasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Subasta.Subasta", b =>
                {
                    b.Property<Guid>("IdSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrecioReferencia")
                        .HasColumnType("int");

                    b.Property<Guid?>("RfxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TipoPreciosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoSubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ValorEstimado")
                        .HasColumnType("int");

                    b.Property<Guid?>("ZonaHorariaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSubasta");

                    b.HasIndex("TipoPreciosId");

                    b.HasIndex("TipoSubastaId");

                    b.ToTable("Subasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Subasta.TipoSubasta", b =>
                {
                    b.Property<Guid>("IdTipoSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("IdTipoSubasta");

                    b.ToTable("TipoSubasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.TipoPrecios.TipoPrecios", b =>
                {
                    b.Property<Guid>("IdTipoPrecios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("IdTipoPrecios");

                    b.ToTable("TipoPrecios");
                });

            modelBuilder.Entity("Holcim.Domain.Entities.ZonaHoraria.ZonaHoraria", b =>
                {
                    b.Property<Guid>("IdZonaHoraria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdZonaHoraria");

                    b.ToTable("ZonaHoraria");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.ItemSubasta.ItemSubasta", b =>
                {
                    b.HasOne("Holcim.AuctionService.Domain.Entities.Subasta.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Region.RegionSubasta", b =>
                {
                    b.HasOne("Holcim.AuctionService.Domain.Entities.Subasta.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Subasta.InvitacionProveedorSubasta", b =>
                {
                    b.HasOne("Holcim.AuctionService.Domain.Entities.Subasta.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Subasta.PreguntaSobreSubasta", b =>
                {
                    b.HasOne("Holcim.AuctionService.Domain.Entities.Subasta.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Subasta.Subasta", b =>
                {
                    b.HasOne("Holcim.AuctionService.Domain.Entities.TipoPrecios.TipoPrecios", "TipoPrecios")
                        .WithMany()
                        .HasForeignKey("TipoPreciosId");

                    b.HasOne("Holcim.AuctionService.Domain.Entities.Subasta.TipoSubasta", "TipoSubasta")
                        .WithMany()
                        .HasForeignKey("TipoSubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPrecios");

                    b.Navigation("TipoSubasta");
                });
#pragma warning restore 612, 618
        }
    }
}
