// <auto-generated />
using System;
using Holcim.AuctionService.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Holcim.AuctionService.Persistence.Migrations
{
    [DbContext(typeof(DataBaseService))]
    [Migration("20250115155925_rondas subasta")]
    partial class rondassubasta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Correo.Correo", b =>
                {
                    b.Property<Guid>("IdCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Html")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCorreo");

                    b.ToTable("Correo");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Estado.Estado", b =>
                {
                    b.Property<Guid>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TipoEstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdEstado");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.ItemSubasta.ItemSubasta", b =>
                {
                    b.Property<Guid>("IdItemSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdItemSubasta");

                    b.HasIndex("SubastaId");

                    b.ToTable("ItemSubasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Mensaje.Mensaje", b =>
                {
                    b.Property<Guid>("IdMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensajes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("visto")
                        .HasColumnType("bit");

                    b.HasKey("IdMensaje");

                    b.ToTable("Mensaje");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.ProveedorSubasta.ProveedorSubasta", b =>
                {
                    b.Property<Guid>("IdProveedorSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdProveedorSubasta");

                    b.HasIndex("SubastaId");

                    b.ToTable("ProveedorSubasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Region.RegionSubasta", b =>
                {
                    b.Property<Guid>("IdRegionSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRegion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdRegionSubasta");

                    b.HasIndex("SubastaId");

                    b.ToTable("RegionSubasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Ronda.ItemsRonda", b =>
                {
                    b.Property<Guid>("IdItemsRonda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Cantidad")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RondaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("valorUnidad")
                        .HasColumnType("bigint");

                    b.HasKey("IdItemsRonda");

                    b.ToTable("ItemsRonda");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Ronda.RespuestaRonda", b =>
                {
                    b.Property<Guid>("RespuestaRondaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ItemsRondaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Respuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioRondaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RespuestaRondaId");

                    b.ToTable("RespuestaRonda");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Ronda.Ronda", b =>
                {
                    b.Property<Guid>("IdRonda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<Guid>("SubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tiempo")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdRonda");

                    b.ToTable("Ronda");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Ronda.UsuarioRonda", b =>
                {
                    b.Property<Guid>("IdIUsuarioRonda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RondaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdIUsuarioRonda");

                    b.ToTable("UsuarioRonda");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Subasta.InvitacionProveedorSubasta", b =>
                {
                    b.Property<Guid>("IdInvitacionProveedorSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdInvitacionProveedorSubasta");

                    b.HasIndex("SubastaId");

                    b.ToTable("InvitacionProveedorSubasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Subasta.Subasta", b =>
                {
                    b.Property<Guid>("IdSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Directo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MejorOferta")
                        .HasColumnType("int");

                    b.Property<Guid>("MonedaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PrecioReferencia")
                        .HasColumnType("int");

                    b.Property<Guid?>("RfxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoOfertaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoSubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ValorEstimado")
                        .HasColumnType("int");

                    b.Property<Guid?>("ZonaHorariaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSubasta");

                    b.HasIndex("TipoOfertaId");

                    b.HasIndex("TipoSubastaId");

                    b.ToTable("Subasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Subasta.TipoSubasta", b =>
                {
                    b.Property<Guid>("IdTipoSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("IdTipoSubasta");

                    b.ToTable("TipoSubasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.TipoPrecios.TipoOferta", b =>
                {
                    b.Property<Guid>("IdTipoOferta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("IdTipoOferta");

                    b.ToTable("TipoPrecios");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.ItemSubasta.ItemSubasta", b =>
                {
                    b.HasOne("Holcim.AuctionService.Domain.Entities.Subasta.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.ProveedorSubasta.ProveedorSubasta", b =>
                {
                    b.HasOne("Holcim.AuctionService.Domain.Entities.Subasta.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Region.RegionSubasta", b =>
                {
                    b.HasOne("Holcim.AuctionService.Domain.Entities.Subasta.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Subasta.InvitacionProveedorSubasta", b =>
                {
                    b.HasOne("Holcim.AuctionService.Domain.Entities.Subasta.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Holcim.AuctionService.Domain.Entities.Subasta.Subasta", b =>
                {
                    b.HasOne("Holcim.AuctionService.Domain.Entities.TipoPrecios.TipoOferta", "TipoOferta")
                        .WithMany()
                        .HasForeignKey("TipoOfertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.AuctionService.Domain.Entities.Subasta.TipoSubasta", "TipoSubasta")
                        .WithMany()
                        .HasForeignKey("TipoSubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoOferta");

                    b.Navigation("TipoSubasta");
                });
#pragma warning restore 612, 618
        }
    }
}
