// <auto-generated />
using System;
using Holcim.ContractsService.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Holcim.ContractsService.Persistence.Migrations
{
    [DbContext(typeof(DataBaseService))]
    [Migration("20241212182530_Contratos")]
    partial class Contratos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Holcim.ContractsService.Domain.Entities.Condiciones.CondicionDinero", b =>
                {
                    b.Property<Guid>("IdCondicionDinero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<Guid>("FechaActulizacion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FechaCreacion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MontoMaximo")
                        .HasColumnType("int");

                    b.Property<int>("MontoMinimo")
                        .HasColumnType("int");

                    b.HasKey("IdCondicionDinero");

                    b.ToTable("CondicionDinero");
                });

            modelBuilder.Entity("Holcim.ContractsService.Domain.Entities.Contratos.Contrato", b =>
                {
                    b.Property<Guid>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActulizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MonedaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Monto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdContrato");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("Holcim.ContractsService.Domain.Entities.Contratos.TipoContrato", b =>
                {
                    b.Property<Guid>("IdTipoContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoContrato");

                    b.ToTable("TipoContrato");
                });

            modelBuilder.Entity("Holcim.ContractsService.Domain.Entities.FlujoAprobacion.FlujoAprobacion", b =>
                {
                    b.Property<Guid>("IdFlujoAprobacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFlujoAprobacion");

                    b.ToTable("FlujoAprobacion");
                });

            modelBuilder.Entity("Holcim.ContractsService.Domain.Entities.Pasos.PasoFlujo", b =>
                {
                    b.Property<Guid>("IdPasoFlujo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CondicionDineroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<Guid>("FlujoAprobacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("IdPasoFlujo");

                    b.HasIndex("CondicionDineroId");

                    b.HasIndex("FlujoAprobacionId");

                    b.ToTable("PasoFlujo");
                });

            modelBuilder.Entity("Holcim.ContractsService.Domain.Entities.Pasos.PasosPerfiles", b =>
                {
                    b.Property<Guid>("IdPasosPerfiles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PasoFlujoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPasosPerfiles");

                    b.HasIndex("PasoFlujoId");

                    b.ToTable("PasosPerfiles");
                });

            modelBuilder.Entity("Holcim.ContractsService.Domain.Entities.Pasos.PasosTipoContrato", b =>
                {
                    b.Property<Guid>("IdPasosTipoContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PasoFlujoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPasosTipoContrato");

                    b.HasIndex("PasoFlujoId");

                    b.HasIndex("TipoContratoId");

                    b.ToTable("PasosTipoContrato");
                });

            modelBuilder.Entity("Holcim.ContractsService.Domain.Entities.Pasos.PasoFlujo", b =>
                {
                    b.HasOne("Holcim.ContractsService.Domain.Entities.Condiciones.CondicionDinero", "CondicionDinero")
                        .WithMany()
                        .HasForeignKey("CondicionDineroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.ContractsService.Domain.Entities.FlujoAprobacion.FlujoAprobacion", "FlujoAprobacion")
                        .WithMany()
                        .HasForeignKey("FlujoAprobacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CondicionDinero");

                    b.Navigation("FlujoAprobacion");
                });

            modelBuilder.Entity("Holcim.ContractsService.Domain.Entities.Pasos.PasosPerfiles", b =>
                {
                    b.HasOne("Holcim.ContractsService.Domain.Entities.Pasos.PasoFlujo", "PasoFlujo")
                        .WithMany()
                        .HasForeignKey("PasoFlujoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PasoFlujo");
                });

            modelBuilder.Entity("Holcim.ContractsService.Domain.Entities.Pasos.PasosTipoContrato", b =>
                {
                    b.HasOne("Holcim.ContractsService.Domain.Entities.Pasos.PasoFlujo", "PasoFlujo")
                        .WithMany()
                        .HasForeignKey("PasoFlujoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holcim.ContractsService.Domain.Entities.Contratos.TipoContrato", "TipoContrato")
                        .WithMany()
                        .HasForeignKey("TipoContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PasoFlujo");

                    b.Navigation("TipoContrato");
                });
#pragma warning restore 612, 618
        }
    }
}
